version: "3.9"

networks:
  monitor:

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitor

  app:
    container_name: app
    build: ./expenses20/.
    ports:
      - "5000:5000"
    volumes:
      - "./expenses20/app.py:/app.py"
      - "./expenses20/const.py:/const.py"
      - "./expenses20/db.py:/db.py"
      - "./expenses20/db_expenses.db:/db_expenses.db"
      - "./expenses20/controllers/user.py:/controllers/user.py"
      - "./expenses20/controllers/expenses.py:/controllers/expenses.py"
      - "./expenses20/controllers/expenses_types.py:/controllers/expenses_types.py"
      - "./expenses20/controllers/statistics.py:/controllers/statistics.py"
    networks:
      - monitor

  example-grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: example-grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - "./monitoring/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
    env_file:
      - "./monitoring/config.monitoring"
    networks:
      - monitor
